global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "math_api"
    metrics_path: /metrics
    scrape_interval: 15s
    static_configs:
      - targets: ["app:8008"]
    # Enable exemplars support
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'http_.*'
        action: keep

  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]

#  - job_name: "redis"
#    static_configs:
#      - targets: [ "cachedb:6379" ]
    # You need redis_exporter

  - job_name: "loki"
    static_configs:
      - targets: [ "loki:3100" ]

  - job_name: "tempo"
    static_configs:
      - targets: [ "tempo:3200" ]
